############################
## config LuckyMan
##########################################################################

### DO NOT CHANGE THE iVersion... If so the plugin will not work
iVersion: 205

## USE EXP COST CHANGE TO FALSE IF YOU DONT WANT PLAYER LOOSE XP
UseExpCost: true

## THIS IS THE LOWER COST : Get a 5% chance to get Super stuff
ExpCostLow: 2

## THIS IS THE MIDDLE COST : Get a +10% chance to get Super stuff
ExpCostMedium: 5

## THIS IS THE HIGH COST : Get a +40% chance to get Super stuff
ExpCostHigh: 10

## DELAY REUSE ALL COMMAND IN SECOND
iSecondDelay: 60

## WORLDS TO ENABLE THIS PLUGIN
listWorlds:
  - world
  - world_nether
  - world_the_end
  